import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { Reveal } from "@/components/Reveal";
import { Button } from "@/components/ui/button";
import { getService } from "@/data/services";
import { getRecommendations } from "@/lib/advisor.functions";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "@tanstack/react-router";
type Recommendation = Extract<Awaited<ReturnType<typeof getRecommendations>>, { ok: true }>["result"];

export const Route = createFileRoute("/advisor")({
  head: () => ({
    meta: [
      { title: "Service Advisor · Online Optic Nova" },
      { name: "description", content: "Describe your business and goals and get a tailored set of services and next steps in under a minute." },
      { property: "og:title", content: "Service Advisor · Online Optic Nova" },
      { property: "og:description", content: "Get a tailored service plan for your business goals." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: AdvisorPage,
});

const budgets = ["Under $1k", "$1k to $5k", "$5k to $15k", "$15k+", "Not sure yet"];
const field = "w-full rounded-sm border border-border bg-transparent px-4 py-3 text-foreground placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none";

function AdvisorPage() {
  const [form, setForm] = useState({ business: "", goals: "", needs: "", budget: "" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<Recommendation | null>(null);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    if (form.business.trim().length < 3 || form.goals.trim().length < 10) {
      setError("Tell us a little about your business and what you want to achieve.");
      return;
    }
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const res = await getRecommendations({ data: form });
      if (res.ok) setResult(res.result);
      else setError(res.error);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const set = (key: keyof typeof form) => (e: { target: { value: string } }) => setForm({ ...form, [key]: e.target.value });

  return (
    <main className="mx-auto max-w-7xl px-5 pb-24 pt-32 md:px-8 md:pt-40">
      <Reveal>
        <h1 className="max-w-3xl font-display text-4xl font-medium leading-[1.08] text-foreground md:text-6xl">
          Not sure where to start? <span className="font-serif italic text-primary">Ask the advisor.</span>
        </h1>
        <p className="mt-6 max-w-xl text-muted-foreground">Describe your business and goals. You will get a recommended mix of our services and clear next steps, generated by AI and reviewed by our team when you get in touch.</p>
      </Reveal>

      <div className="mt-14 grid gap-12 lg:grid-cols-[1fr_1.1fr]">
        <form onSubmit={submit} className="space-y-5">
          <label className="block"><span className="mb-2 block text-sm text-muted-foreground">Your business</span>
            <input className={field} maxLength={300} value={form.business} onChange={set("business")} placeholder="A family bakery in Lagos selling cakes and pastries" /></label>
          <label className="block"><span className="mb-2 block text-sm text-muted-foreground">Goals</span>
            <textarea className={`${field} min-h-28`} maxLength={1500} value={form.goals} onChange={set("goals")} placeholder="Take more online orders and look more professional" /></label>
          <label className="block"><span className="mb-2 block text-sm text-muted-foreground">Current challenges or needs (optional)</span>
            <textarea className={`${field} min-h-24`} maxLength={1500} value={form.needs} onChange={set("needs")} placeholder="No website, inconsistent social posts" /></label>
          <label className="block"><span className="mb-2 block text-sm text-muted-foreground">Budget (optional)</span>
            <select className={field} value={form.budget} onChange={set("budget")}>
              <option value="">Select a range</option>
              {budgets.map((b) => <option key={b} value={b}>{b}</option>)}
            </select></label>
          {error && <p className="text-sm text-destructive" role="alert">{error}</p>}
          <Button type="submit" disabled={loading} className="h-12 rounded-sm px-6">{loading ? "Building your plan..." : "Get recommendations"}</Button>
        </form>

        <div aria-live="polite" className="rounded-md border border-border p-6 md:p-10">
          {!result && !loading && <p className="text-muted-foreground">Your tailored plan will appear here.</p>}
          {loading && <div className="space-y-4">{[0, 1, 2].map((i) => <div key={i} className="h-16 animate-pulse rounded-sm bg-muted" />)}</div>}
          {result && (
            <div>
              <p className="font-serif text-2xl leading-relaxed text-foreground">{result.summary}</p>
              <ol className="mt-8 space-y-6">
                {result.services.map((s) => {
                  const svc = getService(s.slug);
                  if (!svc) return null;
                  return (
                    <li key={s.slug} className="border-l-2 border-primary pl-5">
                      <p className="text-xs uppercase tracking-wider text-primary">{s.priority}</p>
                      <Link to="/services/$slug" params={{ slug: s.slug }} className="mt-1 block font-display text-xl text-foreground hover:text-primary">{svc.title} ↗</Link>
                      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.reason}</p>
                    </li>
                  );
                })}
              </ol>
              <h2 className="mt-10 font-display text-lg text-foreground">Next steps</h2>
              <ol className="mt-4 space-y-3 text-sm text-muted-foreground">
                {result.nextSteps.map((step, i) => <li key={i} className="flex gap-3"><span className="font-display tabular-nums text-primary">{String(i + 1).padStart(2, "0")}</span>{step}</li>)}
              </ol>
              <BookCall result={result} business={form.business} budget={form.budget} />
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

function BookCall({ result, business, budget }: { result: Recommendation; business: string; budget: string }) {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");

  if (!open) return <Button className="mt-8 h-12 rounded-sm px-6" onClick={() => setOpen(true)}>Book a discovery call</Button>;

  const send = async (e: FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !/^\S+@\S+\.\S+$/.test(email.trim())) {
      setError("Please add your name and a valid email.");
      return;
    }
    setSending(true);
    setError("");
    const plan = result.services.map((s) => `${s.priority}: ${getService(s.slug)?.title ?? s.slug}`).join("; ");
    const { error: dbError } = await supabase.from("inquiries").insert({
      name: name.trim().slice(0, 100),
      email: email.trim().slice(0, 255),
      company: business.trim().slice(0, 100) || null,
      service: "Discovery call (Advisor)",
      budget: budget || null,
      message: `Advisor plan. ${result.summary}\nRecommended: ${plan}`.slice(0, 2000),
    });
    setSending(false);
    if (dbError) setError("We could not send your request. Please try again.");
    else navigate({ to: "/thank-you" });
  };

  return (
    <form onSubmit={send} className="mt-8 space-y-4 border-t border-border pt-8">
      <p className="text-sm text-muted-foreground">Leave your details and we will reach out to schedule the call. Your plan is attached automatically.</p>
      <input className={field} placeholder="Your name" aria-label="Your name" maxLength={100} value={name} onChange={(e) => setName(e.target.value)} />
      <input className={field} type="email" placeholder="you@company.com" aria-label="Email" maxLength={255} value={email} onChange={(e) => setEmail(e.target.value)} />
      {error && <p className="text-sm text-destructive" role="alert">{error}</p>}
      <Button type="submit" disabled={sending} className="h-12 rounded-sm px-6">{sending ? "Sending..." : "Request my call"}</Button>
    </form>
  );
}
